version: "3.8"

services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./backend/.env
  backend:
    build: ./backend
    ports:
      - 4000:80
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  backend_logs:
